### ISSUE TITLE
Dold kopia vid massmailutskick

### ISSUE THREAD

**Issue by Saradenrara** [Sveriges-Fontanhus-Riksforbund/Fontanreg#22]
Hej,

vi skickade ut ett massmail till medlemmar ute i arbete & studier, vi fick feedback från en medlem som inte ville att allas emailadresser skulle synas i mailet. Alla 49 mailadresserna syntes i mailet, finns det möjlighet att lägga till så man kan välja dold kopia innan man skickar?

Mvh sara

**Comment by Dan-Svenhall** [comment]
Jag har ändrat nu så varje mottagare bara ser sin egen epostadress.
/ Dan

**Comment by Saradenrara** [comment]
Super! 🙏😊🙏Skickat från min iPhone27 aug. 2024 kl. 19:09 skrev Dan-Svenhall ***@***.***>:﻿
Jag har ändrat nu så varje mottagare bara ser sin egen epostadress.
/ Dan
